### ISSUE TITLE
Wallets

### ISSUE THREAD

**Issue by owittek** [michael-spengler/digitale-waehrungen-wwi19seb#1]
-

**Comment by michael-spengler** [comment]
sent some first qna on ropsten to Olivier https://ropsten.etherscan.io/address/0xB5f5Ebf222Fa2Ae3Ca827E24BEFa7eB50Bf8a10F

testing around on ropsten before doing this on arbitrum...

**Comment by NiklasSchaefer** [comment]
Niklas Schäfer
0x35B00640dF68489856c94c618A0F9fE7db383250
